### ISSUE TITLE
Thirst Glitch

### ISSUE THREAD

**Issue by kenijey** [Terrails/StatsKeeper#1]
ah, it is unplayable a little bit :D i died from thirsty, and i respawned, my thirst is full. But i'm getting damage from thirst but the thirst bar is still full :( and i died again, again, again.. still thirst full :( please help...

**Comment by kenijey** [comment]
AND, i relogged, then what happened.... my thirst is full, and i started to run to know if it is true, and yeah, it was true. it was started to decrease... xD

**Comment by Terrails** [comment]
I'm working on fixing it.

**Comment by kenijey** [comment]
okay, thanks a lot! ^^ be lucky with

**Comment by Terrails** [comment]
Should be fixed in 1.4.1 version. I uploaded it, just have to wait for approval.
