### ISSUE TITLE
Brewing Stand

### ISSUE THREAD

**Issue by LadyTala** [Terrails/StatsKeeper#14]
Anytime I craft and use a brewing stand for 1.12.2 it crashes my minecraft. I have other mods, but took the time to go through each of them to make sure which one it was. Hopefully this gets fixed!

**Comment by Terrails** [comment]
Just tried it and I'm not having this issue... could you give me your FML log with the crash in it just to make sure (its located in logs folder and its called "latest.log")

**Comment by LadyTala** [comment]
It might have not been you! I rechecked to make sure, and yours is working fine again... Its really weird.
[latest.log](https://github.com/Terrails/StatsKeeper/files/1563658/latest.log)

**Comment by LadyTala** [comment]
I think it might be the clover mod I have installed.... I will try again with that mod in there and see what happens.....

**Comment by Terrails** [comment]
There is no crash in that log, but yeah... try to find the mod thats causing it and report it on their github

**Comment by LadyTala** [comment]
Will do!
