### ISSUE TITLE
Custom health increase items no longer consumed on right-click

### ISSUE THREAD

**Issue by Luke616** [Terrails/StatsKeeper#16]
Hello,

Having an issue which has persisted from versions 3.0.0 to 3.0.4. Previously (in updates 2.X.X), I had been using a custom contenttweaker dummy item (has no special effects whatsoever, is just an item with a texture) as the consumable health-increase item for statskeeper in my mod pack. However, as of the 3.0.0 update this item is no longer consumed on right-click even when specified as a health-increase item in the StatsKeeper configs. The player's health does not increase either, there is no effect when clicking the item. I'm not sure what has changed in regards to this feature, but any help fixing it would be greatly appreciated!

Versions:
Stats Keeper 3.0.4 for 1.12.2
Forge 14.23.5.2815

Thanks!
Luke616

**Comment by Terrails** [comment]
Ah I probably know what's causing this issue, will fix it now

**Comment by Terrails** [comment]
Just uploaded it to curseforge, it should be available after they approve it
