### ISSUE TITLE
Health resets to a value of 20 after death, regardless of settings

### ISSUE THREAD

**Issue by Luke616** [Terrails/StatsKeeper#20]
Hello,

Having an issue where player's hearts are being set to a value of 20 (10 hearts) after death. Here is a pastebin of my config file (tldr: min health = 10, max health = 40, start with min = true), and here is a short clip of what is occurring (disregard the unrelated crafttweaker error in the video).

https://pastebin.com/8vD1sghn
https://gfycat.com/querulousfeminineeskimodog

Versions:
Stats Keeper 3.0.5
Forge 14.23.5.2815 for MC 1.12.2

Thank you!
- Luke

**Comment by Terrails** [comment]
Should be fixed now
