### ISSUE TITLE
Creative Mode Bug

### ISSUE THREAD

**Issue by GingerMeow** [Terrails/StatsKeeper#27]
In creative mode, I use /kill command, and after respawn i change gamemode to survival, but I find my health bar is lose and receive any damage I will die.
Mod Version: 1.15.2-4.2.5
Forge Version: 3.1.147

**Comment by Terrails** [comment]
I can't seem to recreate the bug, either way I think I know what might be at fault. Just to confirm, is this singleplayer or multiplayer?

**Comment by Terrails** [comment]
If you have more mods installed, try stats keeper only if you haven't yet. Some other mod might be also modifying your health bar.

**Comment by GingerMeow** [comment]
It's in singleplayer. I will try to recreate the bug without any other mods.
