### ISSUE TITLE
This mod is forcing me to only have 3 hearts.

### ISSUE THREAD

**Issue by Blayyke** [Terrails/StatsKeeper#28]
In 1.16.1, in a new world my player only has 3 hearts max ( 6 health ). I noticed the config has the MAX_HEALTH: 6 and i bumped t hat up to 10 to test, and it made the max health 5. Is this intentional behaviour? I hadn't died so there were no stats to keep after my death.

**Comment by Terrails** [comment]
You configured it the wrong way. Health does not equal hearts. The default player health is 10 hearts or 20 health, so you should set MAX_HEALTH to 20 or you could just disable the health system altogether if you don't want that behaviour.

**Comment by Terrails** [comment]
I'm not sure if I understood this correctly though. Could you please elaborate what exactly is it that you would like to do?

**Comment by Blayyke** [comment]
I wouldn't like to do anything. My player had 3 hearts in total max when i started a fresh world. I had just installed this mod and not touched it before. This was a default setting.

**Comment by Terrails** [comment]
Yeah, I usually have that as a default setting. I should probably disable the health system altogether by default. You can disable the behaviour from the mod by just disabling the system by making "enabled" under "HEALTH_STATS" false. That will return the vanilla behaviour.

**Comment by Terrails** [comment]
Though, if you would like to use the health system you could check the wiki, since there's a ton of interesting things that you can do with your health in there. Its a bit outdated, because I've been delaying to update it, but it should be "understandable".

**Comment by Blayyke** [comment]
I'll have a look. Though for now i just disabled it like you said. I was interested most in the keep food after death anyway 👍
