### ISSUE TITLE
Losing xp with keep xp on

### ISSUE THREAD

**Issue by Aydaym** [Terrails/StatsKeeper#29]
![ezgif-7-1002a95296ee](https://user-images.githubusercontent.com/63841063/90302772-0ffb5880-deec-11ea-959b-f7c17e72c29a.gif)

**Comment by Terrails** [comment]
which version are you using?

**Comment by Aydaym** [comment]
Oh sorry my bad i'm using the latest for fabric StatsKeeper-1.16.1-2.1.4

**Comment by Terrails** [comment]
It should be fixed now.
