### ISSUE TITLE
Amazing Bug (mod compatibility)

### ISSUE THREAD

**Issue by kenijey** [Terrails/StatsKeeper#3]
hello. i just updated the mod from 1.4.5 to 1.5.6, and world started to lag as makes it unplayable from lag
it happens only Multi Mine mod from atomicstryker is installed, and when dig your under (mine) (don't release the left click).
can you help it please? it doesn't happen in v1.4.5. using forge 2308. thank you.

**Comment by Terrails** [comment]
Could you please describe the problem, I installed Multi Mine and my frames are the same, I tried mining under myself and around but nothing happened

**Comment by kenijey** [comment]
hello. i tried it with vanilla now, and reproduced. this is what i did:
used forge 2308, latest multimine and stats keeper.
created a new world, options: enabled cheats, enabled bonus chest
i took the pickaxe from the bonus chest, started to dig my under directly down with my pickaxe.
i did never release the left click, then it started to lag after 15 blocks approximately.
you can see that sometimes you can't see block breaking process or you don't get the dropped blocks.
and you can also try /forge tps to see tps rate.

**Comment by kenijey** [comment]
i can record a video if you want to see also.

**Comment by Terrails** [comment]
I was able to reproduce it... its weird, I'll see what I can do

**Comment by kenijey** [comment]
thank you.

**Comment by Terrails** [comment]
could you try this, it isn't happening to me anymore but try it and we'll see https://www.dropbox.com/s/7y2p83rhqtnenjr/Ingotter-1.5.7.jar?dl=0

**Comment by kenijey** [comment]
ingotter? :D ... trying

**Comment by kenijey** [comment]
no it doesn't work, bug is still happening.

**Comment by Terrails** [comment]
could you try this version on 13.20.0.2309 of forge because I think its something with forge, https://www.dropbox.com/s/2aqkbfry8njhd1v/StatsKeeper-1.5.7.jar?dl=0

**Comment by kenijey** [comment]
Can i do it with forge 2310?

**Comment by Terrails** [comment]
sure just make sure its latest

**Comment by kenijey** [comment]
no, it didn't work on forge 2310.

**Comment by Terrails** [comment]
I don't know whats happening anymore but try to download this file now https://www.dropbox.com/s/7pwhojbp4stri53/Stats%20Keeper-1.5.7.jar?dl=0 I tried it on 2310 on 1.11.2 mc version and it works without any lag in dev workspace and in normal environment.

**Comment by kenijey** [comment]
no, it still happens. i think @atomicstryker should help us.
my style to reproduce the bug:
- install stats keeper that you linked and latest multimine on curseforge
- forge 2310, arguments: -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
- open the game, create a new world that cheats and bonus chest enabled
- get the wooden pickaxe from the chest (wood pickaxe is better to reproduce the bug)
- start to dig your under till bug happens.
i can record a video if you want. i reproduced it many times.

**Comment by Terrails** [comment]
I tried to reproduce it once more but failed to get any lag. This is the video if you want to see if I did something wrong https://puu.sh/w6U9u/d296ceb374.mp4

**Comment by kenijey** [comment]
okay i will record a video tomorrow just like yours. really, thanks so much for dealing with it.

**Comment by Terrails** [comment]
was the issue fixed?

**Comment by kenijey** [comment]
oh, sorry; let me record a video then upload. (incoming in 10 mins approximately)

**Comment by kenijey** [comment]
here it is:
https://www.youtube.com/watch?v=gCTrx9TZcTM
it still happens, used forge 2315

**Comment by AtomicStryker** [comment]
Just so i understand correctly, if you release left click at any time it doesn't happen? Or it only happens if you mine 30+ blocks without letting go?

**Comment by kenijey** [comment]
yes? i did it in the video, i released left click, i stop mining, then started again and happened again, much faster than the first time i start.

**Comment by kenijey** [comment]
see 1:33 in the video.

**Comment by Terrails** [comment]
@AtomicStryker its a really weird bug I don't know how our mods connect to make that kind of issue because I don't mess with left click

**Comment by kenijey** [comment]
haha. yes it's very weird, stats keeper just keeps hunger&saturation, and multi mine just keeps the block break process.
but, it doesn't happen in Stats Keeper 1.4.5.

**Comment by Terrails** [comment]
it could be the Watch thing I added for the config file. I'll disable it and post the link.

**Comment by AtomicStryker** [comment]
o_O Here let me link you the 2 critical files for Multi Mine
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.11.2/MultiMine/src/main/java/atomicstryker/multimine/client/MultiMineClient.java
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.11.2/MultiMine/src/main/java/atomicstryker/multimine/common/MultiMineServer.java

Essentially, i coremod PlayerControllerMP which holds the float value of how much the block being mined is broken and add callback functionality. The client sends "mining progress" packets to the server, which keeps a map of partially mined blocks and re-distributes them to all players. If a player stops mining a block, the vanilla behaviour is to snap back to 0 progress, however Multi Mine keeps the obtained progress, and if a player hits the same block again, uses the mentioned callback to substitute the "fresh" mining progress with the previous, partially completed value.

**Comment by kenijey** [comment]
which one should i do? both? i'm trying it on singleplayer.

**Comment by Terrails** [comment]
Hmm weird, I disabled WatchService (I use this for when you edit config file in game it automatically syncs with game, something like the config gui but for the file itself) and tried it myself, got the pickaxe from the chest and mined until it broke without any lag. Could be WatchService's fault than but I don't see why.

**Comment by kenijey** [comment]
i still am using 1.4.5. why did u add that feature? it was working fine already

**Comment by Terrails** [comment]
its useful if you want to edit config file instead of going in mod options and editing it in GUI when the game is running

**Comment by Terrails** [comment]
Could you just confirm to its not happening with the newest file

**Comment by kenijey** [comment]
Newest file? I already used newest file in the video

**Comment by Terrails** [comment]
this one: https://www.dropbox.com/s/w3z0laeoh79f491/Stats%20Keeper-1.5.7.jar?dl=0

**Comment by kenijey** [comment]
uhm yes, it's not happening, i think.

**Comment by Terrails** [comment]
great I'll release an update with configurable setting for that config watcher

**Comment by kenijey** [comment]
uhm, please do it for 1.12 :D

**Comment by Terrails** [comment]
I'll slowly start updating to 1.12 but will take some time if a lot has changed

**Comment by kenijey** [comment]
okay. get luck with. @AtomicStryker you too :D
