### ISSUE TITLE
setting up config

### ISSUE THREAD

**Issue by Petrisis** [Terrails/StatsKeeper#33]
maybe its more a question how to config rather than an issue..

i want the players don't be affected by healthchanges through StatsKeeper at all. thus i want them to join the world with 20 HP and respawn with 20 HP. 

```
[...]
[health]
	enabled = false
	[health.values]
		maxHealthAmount = 1024
		minHealthAmount = 20
		deathDecreasedHealthAmount = 0
		startingHealthAmount = "MIN"
	[health.additional]
		configChangeReset = ["MIN_HEALTH", "MAX_HEALTH", "STARTING_HEALTH"]
		healthChangeMessage = true
		hardcoreMode = false
		healthThresholds = [-20, 20]
		regenerativeItems = ["minecraft:nether_star = 1"]
```

as you can see i disabled the hole module, set min to 20 and disabled decrease. but it keeps me spawning (first join & respawn) with 6 HP! 
also i'm not quite sure what `healthThresholds ` does.. 

Versions:
Minecraft version 1.16.5
StatsKeeper version 5.3.12

**Comment by Terrails** [comment]
I cannot reproduce this. The player health is set to default 20 when enabled is false. The only thing I can recommend to you is to delete your config file, generate a new one and then just disable the whole module via "enabled".
