### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by megagnarxd** [Terrails/StatsKeeper#36]
When i die, and if i have above 20 health (10 hearts), I will not spawn with the full amount of hearts. Here is my config: https://pastebin.com/B9HbikGx

**Comment by Terrails** [comment]
Did you try to recreate this issue without the mod installed? I can't see what would cause this since basically everything that touches health is disabled in your config. I'll look into it if it doesn't happen without the mod.

**Comment by megagnarxd** [comment]
The mod used is paraglider. I have no idea what you meant by disabling the mod paraglider. If so, I am unable to get above 10 hearts. Anything below 10 hearts is fine. Excess hearts after 10, using the paraglider mod, will not work.

**Comment by Terrails** [comment]
Then its a bug in paraglider, this has nothing to do with statskeeper.

**Comment by megagnarxd** [comment]
okay, thanks for the response!
