### ISSUE TITLE
No thirst config

### ISSUE THREAD

**Issue by AndreySlower** [Terrails/StatsKeeper#37]
MC 1.16.5
TAN 4.1.0.9
Stats keeper 6.1.0/6.0.0

For some reason there is no config options for thirst. And after death thirst resets to max. Everything else works fine.

**Comment by Terrails** [comment]
Ah, I disabled this due to ToughAsNails not being updated for a few years. Gonna look into implementing it again.

**Comment by AndreySlower** [comment]
> Ah, I disabled this due to ToughAsNails not being updated for a few years. Gonna look into implementing it again.

tnahks
