### ISSUE TITLE
Crashes with Spells&Shields

### ISSUE THREAD

**Issue by Albhis** [Terrails/StatsKeeper#39]
I was hoping either this or Health Overlay would help the overlay to the spells&shields' extra mana bar (basically adds 1 or 2 HUD bars between breath and hunger but this mod crashes it.

>The crash report
[crash-2022-10-11_03.36.56-server.txt](https://github.com/Terrails/StatsKeeper/files/9753816/crash-2022-10-11_03.36.56-server.txt)

It could be a neat and pretty compatibility to have, but I'm also content with just having it marked noncompatable or something.

**Comment by Albhis** [comment]
Oh, completely forgot to add!

**Comment by Albhis** [comment]
Ack, Pressed the wrong buttons
I meant to add that purple and green would be good colors IF you do actually want to make it function

**Comment by Terrails** [comment]
Oops, it's probably my fault. I didn't update the mod to the latest forge version. If you could try downgrading a few versions until I get a fix ready in a few hours.

**Comment by Terrails** [comment]
I would honestly just like Health Overlay to stay a colored health/absorption only mod, so probably the best to request this feature on Spells & Shields' issue tracker as it would be a slightly annoying workaround to make this work in an external mod.
