### ISSUE TITLE
Config makes dying impossible

### ISSUE THREAD

**Issue by MasterFee** [Terrails/StatsKeeper#4]
The default value for the "Max Health" should be 20 otherwise it makes it impossible to die. Right now the config generates with a value of 0 so the Player should literally have no health but what happens instead is that you constantly regenerate health when you take damage. Even the /kill command can't "really" kill you, it just takes you to the death screen and if you try to respawn you get revived where you died with your inventory and full health - then again immortal to any damage.
Could fix the problem by setting the "Max Health" value to a number greater than 0.

**Comment by Terrails** [comment]
should be fixed in the newest version.
