### ISSUE TITLE
[Enhancement] Config for starting with min health

### ISSUE THREAD

**Issue by grundyboy34** [Terrails/StatsKeeper#7]
Currently the configs allow setting a max and minimum health, but the player always starts the game with 10 hearts. I think it'd be really useful to have a boolean to start players with a health equal to the minimum health. 
Also, I'm using version 1.10.2, so having this on that version would be greatly appreciated.

**Comment by Terrails** [comment]
I can't do it for 1.10, but for 1.11 and 1.12 yes, almost everyone switched to 1.11/1.12 now.

**Comment by grundyboy34** [comment]
Thank you, that'd be great! I can probably backport the versions for you if you wanna open a new branch for me to pull request into afterwards.

**Comment by Terrails** [comment]
Just made a 1.10.x branch so just make a pull request after you're done.

**Comment by Terrails** [comment]
here that should do it, just make a pull request to 1.10.x
